#!/usr/bin/python3
import pyautogui
import sys
from colorama import Fore, Back, Style 

try:
	print(Fore.BLUE + "[+]" + " Stablizing using " + Style.RESET_ALL + Fore.GREEN + sys.argv[1])
	pyautogui.press('f12')    
	pyautogui.write( sys.argv[1] +' -c \'import pty;pty.spawn(\"/bin/bash\")\'')
	pyautogui.press('enter')
	print(Fore.GREEN + "[+]" , end="")
	print(" Spawned /bin/bash")
	pyautogui.hotkey('ctrl' , 'z')
	pyautogui.write('stty raw -echo')
	pyautogui.press('enter')
	print(Fore.GREEN + "[+]" , end="")
	print(" Added tab completion")
	pyautogui.write('fg')
	for i in range(2):
	    pyautogui.press('enter')
	pyautogui.write('export TERM=xterm')
	pyautogui.press('enter')
	print(Fore.GREEN + "[+]" , end="")
	print(" Added power to clear the screen")
	pyautogui.write('clear')
	pyautogui.press('enter')
	print(Fore.RED + "[#] BOOM" , end="")
	print(". Wiped everything")
except:
	print(Fore.RED + "[-]" , end="")
	print(" No arguments given")
	print(Fore.BLUE + "[*]" , end="")
	print(" Stablizing using default " + Fore.GREEN + "python3")
	pyautogui.press('f12')    
	pyautogui.write('python3 -c \'import pty;pty.spawn(\"/bin/bash\")\'')
	pyautogui.press('enter')
	print(Fore.GREEN + "[+]" , end="")
	print(" Spawned /bin/bash")
	pyautogui.hotkey('ctrl' , 'z')
	pyautogui.write('stty raw -echo')
	pyautogui.press('enter')
	print(Fore.GREEN + "[+]" , end="")
	print(" Added tab completion")
	pyautogui.write('fg')
	for i in range(2):
	    pyautogui.press('enter')
	pyautogui.write('export TERM=xterm')
	pyautogui.press('enter')
	print(Fore.GREEN + "[+]" , end="")
	print(" Added power to clear the screen")
	pyautogui.write('clear')
	pyautogui.press('enter')
	print(Fore.RED + "[#] BOOM" , end="")
	print(". Wiped everything")